Feature/content editor docs
amplience/dc-extensions-sdk pull request #49
Opened 2021-09-10 11:54 UTC by dev-warner

2021-09-13 11:38 UTC, pixelscript requested changes

2021-09-13 11:38 UTC, pixelscript commented on README.md
> +You can get a boolean value weather a piece of content is valid
weather should be whether

2021-09-13 11:38 UTC, pixelscript commented on README.md
> +For syncing your model with Dynamic Content on content changes propergated outside the extension e.g delivery key change
propagated?

2022-02-16 11:41 UTC, srweeks commented
merged into LukeT-Amplience:feature/Extensions-SDK-API-Changes already

2022-02-16 11:41 UTC, closed without merging